services:
  frontend:
    build:
      context: .  # ðŸ‘ˆ à¸Šà¸µà¹‰à¹„à¸›à¸—à¸µà¹ˆà¹‚à¸Ÿà¸¥à¹€à¸”à¸­à¸£à¹Œà¸›à¸±à¸ˆà¸ˆà¸¸à¸šà¸±à¸™ (Trippify-F/)
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - backend-network
    command: npm run dev

networks:
  backend-network:
    driver: bridge
